// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;
const SUPABASE_PROJECT_ID = import.meta.env.VITE_SUPABASE_PROJECT_ID || getProjectIdFromUrl(SUPABASE_URL);

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing Supabase environment variables: VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY');
}

function getProjectIdFromUrl(url: string | undefined) {
  if (!url) return '';

  try {
    return new URL(url).hostname.split('.')[0] || '';
  } catch {
    return '';
  }
}

export const supabaseAuthStorageKey = SUPABASE_PROJECT_ID
  ? `sb-${SUPABASE_PROJECT_ID}-auth-token`
  : undefined;

export const clearSupabaseAuthStorage = () => {
  if (supabaseAuthStorageKey) {
    localStorage.removeItem(supabaseAuthStorageKey);
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: supabaseAuthStorageKey ? { storageKey: supabaseAuthStorageKey } : undefined,
});
